/**
 * Seed 50+ opportunities for development. Run: npm run seed (or node src/seed.js)
 * Requires MONGODB_URI in .env
 */
import 'dotenv/config';
import mongoose from 'mongoose';
import Opportunity from './models/Opportunity.js';

const baseDate = () => new Date(Date.now() + Math.floor(Math.random() * 90 + 14) * 24 * 60 * 60 * 1000);

const opportunities = [
  { title: 'Software Development Intern', company: 'Safaricom', type: 'internship', description: 'Join our technology team to build and maintain digital products used by millions. Work with modern stacks and learn from senior engineers.', requirements: ['Computer Science or related degree', 'Basic programming in any language', 'Good communication skills'], location: 'Nairobi', duration: '3-6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Industrial Attachment - Electrical Engineering', company: 'Kenya Power', type: 'attachment', description: 'Gain hands-on experience in power distribution and grid operations. Suitable for electrical engineering students.', requirements: ['Enrolled in Electrical Engineering', 'Recommendation letter from institution', 'Valid student ID'], location: 'Nairobi / Mombasa', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Business Analytics Intern', company: 'KCB Group', type: 'internship', description: 'Support the analytics team in reporting, dashboards, and data-driven decision making. Exposure to banking operations.', requirements: ['Business, Statistics, or IT background', 'Excel proficiency', 'Interest in data'], location: 'Nairobi', duration: '6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Finance & Accounting Attachment', company: 'Equity Bank', type: 'attachment', description: 'Industrial attachment in finance and accounting. Assist with reconciliations, reporting, and audit support.', requirements: ['Accounting or Finance student', 'Recommendation letter', 'CPA part 1 or equivalent'], location: 'Nairobi', duration: '3 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'Network Engineering Intern', company: 'Safaricom', type: 'internship', description: 'Support network planning and operations. Exposure to telecom infrastructure and monitoring tools.', requirements: ['Telecommunications or Computer Engineering', 'Basic networking knowledge'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Customer Experience Intern', company: 'Safaricom', type: 'internship', description: 'Work with the CX team on customer insights, journey mapping, and service improvement initiatives.', requirements: ['Marketing, Business, or related', 'Strong communication skills'], location: 'Nairobi', duration: '3-6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Mechanical Engineering Attachment', company: 'Kenya Power', type: 'attachment', description: 'Industrial attachment in mechanical maintenance and plant operations. Hands-on with equipment and safety procedures.', requirements: ['Mechanical Engineering student', 'Recommendation letter', 'Valid student ID'], location: 'Nairobi / Thika', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Retail Banking Intern', company: 'KCB Group', type: 'internship', description: 'Learn retail banking operations, customer onboarding, and branch processes.', requirements: ['Business or Finance background', 'Customer service orientation'], location: 'Nairobi', duration: '6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'Digital Marketing Intern', company: 'Equity Bank', type: 'internship', description: 'Support digital campaigns, social media, and content. Exposure to fintech marketing.', requirements: ['Marketing or Communications', 'Familiarity with social media'], location: 'Nairobi', duration: '3-6 months', category: 'Marketing', applicationFee: 350, deadline: baseDate() },
  { title: 'Human Resources Attachment', company: 'Safaricom', type: 'attachment', description: 'Industrial attachment in HR: recruitment, onboarding, and HR operations.', requirements: ['HR or Business student', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'HR', applicationFee: 350, deadline: baseDate() },
  { title: 'Data Science Intern', company: 'Safaricom', type: 'internship', description: 'Work with data scientists on analytics, ML models, and reporting pipelines.', requirements: ['Statistics, CS, or related', 'Python or R basics'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Civil Engineering Attachment', company: 'Kenya Power', type: 'attachment', description: 'Attachment in civil works: substations, foundations, and construction oversight.', requirements: ['Civil Engineering student', 'Recommendation letter'], location: 'Various', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Risk & Compliance Intern', company: 'KCB Group', type: 'internship', description: 'Support risk assessment, compliance checks, and regulatory reporting.', requirements: ['Finance, Law, or Business', 'Attention to detail'], location: 'Nairobi', duration: '6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'Software Testing Intern', company: 'Equity Bank', type: 'internship', description: 'Manual and automated testing of banking applications. Learn QA processes.', requirements: ['CS or related', 'Interest in testing'], location: 'Nairobi', duration: '3-6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Procurement Attachment', company: 'Kenya Power', type: 'attachment', description: 'Industrial attachment in procurement and supply chain. Tendering and vendor management.', requirements: ['Procurement or Supply Chain student', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Frontend Development Intern', company: 'Safaricom', type: 'internship', description: 'Build and maintain web and mobile frontends. React/JavaScript focus.', requirements: ['CS or related', 'HTML/CSS/JS basics'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Backend Development Intern', company: 'KCB Group', type: 'internship', description: 'Develop and maintain APIs and backend services. Java/Node exposure.', requirements: ['CS or related', 'Programming basics'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Audit Attachment', company: 'Equity Bank', type: 'attachment', description: 'Internal audit attachment. Testing controls and documenting findings.', requirements: ['Accounting or Audit student', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'Cybersecurity Intern', company: 'Safaricom', type: 'internship', description: 'Support security operations: monitoring, incident response, and awareness.', requirements: ['CS or Information Security', 'Interest in security'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Operations Intern', company: 'Co-operative Bank', type: 'internship', description: 'Support day-to-day banking operations and process improvement.', requirements: ['Business or Finance', 'Organized and detail-oriented'], location: 'Nairobi', duration: '3-6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Legal Attachment', company: 'KCB Group', type: 'attachment', description: 'Legal department attachment. Contracts, compliance, and corporate legal support.', requirements: ['Law student', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Legal', applicationFee: 350, deadline: baseDate() },
  { title: 'Product Management Intern', company: 'Safaricom', type: 'internship', description: 'Work with product teams on requirements, roadmaps, and user research.', requirements: ['Business, CS, or Design', 'Strong communication'], location: 'Nairobi', duration: '6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Electrical Attachment - Distribution', company: 'Kenya Power', type: 'attachment', description: 'Distribution network attachment. Metering, lines, and field operations.', requirements: ['Electrical Engineering student', 'Recommendation letter'], location: 'Various', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Treasury Intern', company: 'Equity Bank', type: 'internship', description: 'Support treasury operations: liquidity, FX, and money markets.', requirements: ['Finance or Economics', 'Numerical skills'], location: 'Nairobi', duration: '6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'UX Design Intern', company: 'Safaricom', type: 'internship', description: 'User research, wireframes, and prototypes for digital products.', requirements: ['Design or related', 'Portfolio or coursework'], location: 'Nairobi', duration: '3-6 months', category: 'Design', applicationFee: 350, deadline: baseDate() },
  { title: 'Credit Analysis Intern', company: 'KCB Group', type: 'internship', description: 'Support credit assessment and loan portfolio analysis.', requirements: ['Finance or Business', 'Excel and analytical skills'], location: 'Nairobi', duration: '6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'DevOps Intern', company: 'Safaricom', type: 'internship', description: 'CI/CD, cloud infrastructure, and monitoring. AWS/Kubernetes exposure.', requirements: ['CS or related', 'Linux and scripting basics'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Marketing Attachment', company: 'Equity Bank', type: 'attachment', description: 'Marketing department attachment. Campaigns, branding, and events.', requirements: ['Marketing student', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Marketing', applicationFee: 350, deadline: baseDate() },
  { title: 'GIS & Mapping Attachment', company: 'Kenya Power', type: 'attachment', description: 'Geographic information systems and network mapping. Field and office work.', requirements: ['GIS, Geomatics, or related', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Communications Intern', company: 'Safaricom', type: 'internship', description: 'Internal and external communications. Content, PR, and stakeholder engagement.', requirements: ['Communications or Journalism', 'Writing skills'], location: 'Nairobi', duration: '3-6 months', category: 'Marketing', applicationFee: 350, deadline: baseDate() },
  { title: 'Investment Banking Intern', company: 'KCB Group', type: 'internship', description: 'Support M&A, capital markets, and advisory. Financial modeling exposure.', requirements: ['Finance or Economics', 'Strong Excel'], location: 'Nairobi', duration: '6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'Mobile Development Intern', company: 'Equity Bank', type: 'internship', description: 'Android/iOS or cross-platform mobile app development.', requirements: ['CS or related', 'Mobile or web dev basics'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Supply Chain Attachment', company: 'Safaricom', type: 'attachment', description: 'Procurement, logistics, and vendor management attachment.', requirements: ['Supply Chain or Business', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Database Administration Intern', company: 'KCB Group', type: 'internship', description: 'Database design, tuning, and backup. Oracle/SQL Server exposure.', requirements: ['CS or related', 'SQL basics'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Agribusiness Intern', company: 'Equity Bank', type: 'internship', description: 'Support agribusiness lending and farmer outreach programs.', requirements: ['Agriculture or Business', 'Interest in agri finance'], location: 'Nairobi / Regional', duration: '3-6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Renewable Energy Attachment', company: 'Kenya Power', type: 'attachment', description: 'Solar, wind, or geothermal projects. Technical and project support.', requirements: ['Engineering or Energy student', 'Recommendation letter'], location: 'Various', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Cloud Solutions Intern', company: 'Safaricom', type: 'internship', description: 'Cloud architecture and migration. AWS/Azure exposure.', requirements: ['CS or related', 'Networking and OS basics'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Branch Operations Intern', company: 'Co-operative Bank', type: 'internship', description: 'Branch operations, customer service, and cash handling procedures.', requirements: ['Business or Finance', 'Customer focus'], location: 'Nairobi / Mombasa', duration: '3-6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'Research & Strategy Intern', company: 'KCB Group', type: 'internship', description: 'Market research, competitor analysis, and strategy support.', requirements: ['Business or Economics', 'Analytical writing'], location: 'Nairobi', duration: '6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Quality Assurance Attachment', company: 'Safaricom', type: 'attachment', description: 'QA processes, test cases, and defect tracking. Software and process quality.', requirements: ['CS or related', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Microfinance Intern', company: 'Equity Bank', type: 'internship', description: 'Microfinance and inclusive banking. Field and office exposure.', requirements: ['Business or Finance', 'Interest in financial inclusion'], location: 'Nairobi / Regional', duration: '3-6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'Telecom Engineering Attachment', company: 'Safaricom', type: 'attachment', description: 'Radio access network, transmission, and site operations.', requirements: ['Telecommunications or Electrical', 'Recommendation letter'], location: 'Nairobi / Regional', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Business Development Intern', company: 'KCB Group', type: 'internship', description: 'Support BD team on proposals, partnerships, and growth initiatives.', requirements: ['Business or Marketing', 'Communication skills'], location: 'Nairobi', duration: '6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'IT Support Intern', company: 'Equity Bank', type: 'internship', description: 'Help desk, user support, and basic infrastructure. First-line IT support.', requirements: ['IT or CS', 'Customer service'], location: 'Nairobi', duration: '3-6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Environmental & Sustainability Attachment', company: 'Kenya Power', type: 'attachment', description: 'Environmental compliance, ESIA, and sustainability reporting.', requirements: ['Environmental Science or related', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'API Development Intern', company: 'Safaricom', type: 'internship', description: 'Build and maintain APIs for internal and partner integrations.', requirements: ['CS or related', 'REST API basics'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Corporate Banking Intern', company: 'KCB Group', type: 'internship', description: 'Corporate lending, relationship management, and credit support.', requirements: ['Finance or Business', 'Analytical skills'], location: 'Nairobi', duration: '6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'Content Writing Intern', company: 'Equity Bank', type: 'internship', description: 'Blog posts, social content, and internal communications.', requirements: ['Communications or English', 'Writing samples'], location: 'Nairobi', duration: '3-6 months', category: 'Marketing', applicationFee: 350, deadline: baseDate() },
  { title: 'Project Management Intern', company: 'Safaricom', type: 'internship', description: 'Support project planning, tracking, and reporting. Agile/Scrum exposure.', requirements: ['Business or CS', 'Organized'], location: 'Nairobi', duration: '6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Metering & Billing Attachment', company: 'Kenya Power', type: 'attachment', description: 'Metering systems, billing processes, and revenue assurance.', requirements: ['Engineering or IT student', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Fraud Prevention Intern', company: 'KCB Group', type: 'internship', description: 'Support fraud detection, investigations, and prevention initiatives.', requirements: ['Finance, CS, or related', 'Attention to detail'], location: 'Nairobi', duration: '6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'E-commerce Intern', company: 'Safaricom', type: 'internship', description: 'Support e-commerce and digital products. Catalog, payments, and UX.', requirements: ['Business or CS', 'Interest in digital commerce'], location: 'Nairobi', duration: '3-6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Wealth Management Intern', company: 'Equity Bank', type: 'internship', description: 'Support wealth and asset management. Client onboarding and research.', requirements: ['Finance or Economics', 'Interest in investments'], location: 'Nairobi', duration: '6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'Scrum Master Intern', company: 'Safaricom', type: 'internship', description: 'Facilitate agile ceremonies and support delivery teams.', requirements: ['CS or Business', 'Interest in agile'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Safety & Health Attachment', company: 'Kenya Power', type: 'attachment', description: 'Occupational safety, risk assessments, and safety campaigns.', requirements: ['Occupational Health or Engineering', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Partnerships Intern', company: 'KCB Group', type: 'internship', description: 'Support partnership and ecosystem initiatives. Fintech and corporate partners.', requirements: ['Business or related', 'Communication skills'], location: 'Nairobi', duration: '6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Business Intelligence Intern', company: 'Equity Bank', type: 'internship', description: 'BI tools, dashboards, and reporting. Data visualization and SQL.', requirements: ['Business, CS, or Statistics', 'Excel and SQL'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Innovation Lab Intern', company: 'Safaricom', type: 'internship', description: 'Work with innovation team on pilots, hackathons, and new product ideas.', requirements: ['Any discipline', 'Creative and collaborative'], location: 'Nairobi', duration: '3-6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Transmission Planning Attachment', company: 'Kenya Power', type: 'attachment', description: 'Transmission network planning and grid studies.', requirements: ['Electrical Engineering student', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Customer Insights Intern', company: 'KCB Group', type: 'internship', description: 'Customer research, NPS, and feedback analysis.', requirements: ['Marketing or Business', 'Analytical skills'], location: 'Nairobi', duration: '6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Fintech Product Intern', company: 'Equity Bank', type: 'internship', description: 'Support digital banking products. EKYC, mobile banking, and integrations.', requirements: ['CS or Business', 'Interest in fintech'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Infrastructure Intern', company: 'Safaricom', type: 'internship', description: 'Data center and network infrastructure. Monitoring and maintenance.', requirements: ['IT or Engineering', 'Hardware and networking basics'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Corporate Affairs Attachment', company: 'Kenya Power', type: 'attachment', description: 'Stakeholder engagement, CSR, and community relations.', requirements: ['Communications or Social Science', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Channel Management Intern', company: 'KCB Group', type: 'internship', description: 'Support channel strategy: branches, agents, and digital channels.', requirements: ['Business or Marketing', 'Analytical'], location: 'Nairobi', duration: '6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Compliance Intern', company: 'Equity Bank', type: 'internship', description: 'Regulatory compliance, AML/KYC support, and policy updates.', requirements: ['Law, Finance, or Business', 'Detail-oriented'], location: 'Nairobi', duration: '6 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'IoT & M2M Intern', company: 'Safaricom', type: 'internship', description: 'IoT solutions, M2M connectivity, and smart solutions support.', requirements: ['CS or Engineering', 'Interest in IoT'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Generation Attachment', company: 'Kenya Power', type: 'attachment', description: 'Power generation plants. Thermal, hydro, or geothermal exposure.', requirements: ['Electrical or Mechanical Engineering', 'Recommendation letter'], location: 'Various', duration: '3 months', category: 'Engineering', applicationFee: 350, deadline: baseDate() },
  { title: 'Digital Lending Intern', company: 'KCB Group', type: 'internship', description: 'Support digital lending products and credit scoring models.', requirements: ['Finance or CS', 'Data interest'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Brand Management Intern', company: 'Equity Bank', type: 'internship', description: 'Brand guidelines, campaigns, and visual identity support.', requirements: ['Marketing or Design', 'Creative'], location: 'Nairobi', duration: '3-6 months', category: 'Marketing', applicationFee: 350, deadline: baseDate() },
  { title: 'Platform Engineering Intern', company: 'Safaricom', type: 'internship', description: 'Platform services: APIs, gateways, and developer tools.', requirements: ['CS or related', 'API and cloud basics'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Revenue Assurance Attachment', company: 'Kenya Power', type: 'attachment', description: 'Revenue assurance and loss reduction initiatives.', requirements: ['Engineering or Finance student', 'Recommendation letter'], location: 'Nairobi', duration: '3 months', category: 'Finance', applicationFee: 350, deadline: baseDate() },
  { title: 'Agile Coach Intern', company: 'KCB Group', type: 'internship', description: 'Support agile adoption and team coaching. Ceremonies and metrics.', requirements: ['CS or Business', 'Interest in agile'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
  { title: 'Customer Success Intern', company: 'Equity Bank', type: 'internship', description: 'Support enterprise and SME customer success and onboarding.', requirements: ['Business or related', 'Customer focus'], location: 'Nairobi', duration: '3-6 months', category: 'Business', applicationFee: 350, deadline: baseDate() },
  { title: 'Data Engineering Intern', company: 'Safaricom', type: 'internship', description: 'Data pipelines, ETL, and data warehouse support.', requirements: ['CS or related', 'SQL and scripting'], location: 'Nairobi', duration: '6 months', category: 'Technology', applicationFee: 350, deadline: baseDate() },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  await Opportunity.deleteMany({});
  await Opportunity.insertMany(opportunities);
  console.log('Seeded', opportunities.length, 'opportunities');
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
